version: '3.8'

services:
  discord-bot:
    build: .
    container_name: my-discord-bot
    volumes:
      # config.json을 컨테이너에 마운트
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
    # 로그 설정
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"